### ISSUE TITLE
Wrong url on Worker machine email functionality

### ISSUE THREAD

**Issue by gnrcampos** [dusterio/laravel-aws-worker#1]
Hi mate, I've been strugglin with something for the past hours or so and maybe you can point me in the right direction here. I've been using your lib for some time now (congratulations, it's amazing!) and I'm having an error when I try to send an email asynchronously. The blade template for the email is this one, very simple:
`Click here to reset your password: {{ url('/password/reset/' . $token) }}`
But even though I have the right url set on my `config/app.php` file it keeps sending me the wrong link, like this:
`Click here to reset your password: http://localhost/password/reset/f2bffeaac16ba3765aa4404c40f5b13675e5bb1cb2abbdbc7ba5f0af655e4969`
If I change the queue driver to `sync` and execute the code manually inside the worker machine it works perfectly but as soon as I get back to using the `sqs` driver. Do you reckon this has something to do with the lib itself?
Thank you very much for the lib and the possible help =)
Cheers

**Comment by dusterio** [comment]
Hi!

It sounds like your APP_URL is not set/available when running a webhook.

Do you have APP_URL set in your environment (in AWS worker's configuration)?
Do you have clear_env set to 'no' in your PHP FPM config? So that OS environment is visible to PHP

**Comment by gnrcampos** [comment]
Thank you for your quick response. I didn't have `APP_URL` set so I did it and the problem is still there. I can't find the `php-fpm.conf` file to set the `clear_env` to `no` though. However, when I run `php artisan tinker` and do a `getenv('APP_URL')` I get the correct value so it should be working... Any other ideas?

**Comment by dusterio** [comment]
This is not necessarily interconnected - your tinker is a CLI environment, and your failing request, as far as I understand, is a web request (and therefore is an FPM environment). So it could be that your PHP-FPM doesn't have the same environment variables, particularly APP_URL? Easy to test that, try to echo env('APP_URL') in one of your controller methods, and do a web request?

**Comment by gnrcampos** [comment]
Ok, what I did was I changed the return of my `Route::get('/')` method to 'return env('APP_URL')'. After that I did a `wget localhost` and the return was the correct url, so I guess that's not the problem yet =/

**Comment by dusterio** [comment]
Try changing the default value of APP_URL in config/app.php? It's a workaround but at least we will see for sure it's not about APP_URL

**Comment by gnrcampos** [comment]
Manually set the `'url'` parameter inside the `config/app.php` to `test.com` and it still gives me `http://localhost` on the email.

**Comment by gnrcampos** [comment]
Still haven't fixed it =/

**Comment by dusterio** [comment]
Sorry I know! But it's just not related to this package directly, that's why I closed the issue!

So, no luck on this?

**Comment by gnrcampos** [comment]
No worries... Yeah still no luck, what I did was I hardcode the url, bad solution but it's working until I find the real issue.

**Comment by graphem** [comment]
I got the same issue and I am totally clueless. Anyone has found a fix or potential solution?

**Comment by gnrcampos** [comment]
@graphem I found one. Still not sure why the error itself occurs, but those are the steps I used:
1- Create a config file for your env variables inside the /config folder with all of the values you will need. Example:

    return [
        'value1' => env("VALUE_1"),
        'value2' => env("VALUE_2"),
        'value3' => env("VALUE_3"),
    ];

2- Create a post deploy hook script to cache your config. For that, you would create a folder called .ebextensions inside your project's root folder and add a file with the following content:

    commands:
        create_post_dir:
            command: "mkdir /opt/elasticbeanstalk/hooks/appdeploy/post"
            ignoreErrors: true
    files:
        "/opt/elasticbeanstalk/hooks/appdeploy/post/99_laravel_optimization.sh":
            mode: "000755"
            owner: root
            group: root
            content: |
                #!/usr/bin/env bash
                cd /var/app/current
                sudo php artisan optimize
                sudo php artisan config:cache
                sudo php artisan route:cache

Explanation of what's going on:
When you deploy your application, this command will run and create a shell script inside the hooks folder. After the deploy is complete the hook scripts are called and create the cache files. For this specific error the second command, `sudo php artisan config:cache`, is enough but I don't see why you wouldn't use the other two. If you are not using this commands you should try them locally first and make sure they won't break your application.

3- Now you can replace your calls to `env('VALUE_1')` for `config('your_config_file.value1')`

**Comment by eneskaya** [comment]
I know this issue is old but I recently stumbled upon the same problem. I noticed that when you use the `url()` helper method the actual output depends on the way you call that method. So, lets say you have `APP_URL=https://example.com` and a controller method which returns `url('test')` then you make a usual GET request by going to the specified route which returns the before mentioned, let’s say from the domain `test.com`. The output will then be `https://test.com/test`. Laravel ignores or overwrites the `APP_URL` in this case. When you execute the `url` helper in a tinker session though the result will be `https://example.com/test`. And as SQS posts new jobs with an origin of `https://localhost` you get this unexpected URL’s in your mail.  

**Solution:**

In your `AppServiceProvider`s boot-method call: `URL::forceRootUrl(env('APP_URL'));` This forces the `url` helper to use the APP_URL as the base url for generating URLs.

**Comment by sebestenyb** [comment]
If you take a look into your `config/app.php` there's a clear indication:

```    /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
    */

    'url'    => env('APP_URL', 'http://localhost'),
```

This config value only used in the console.
In other cases Laravel uses the request, and with this package and ElasticBeanstalk the request comes as http://localhost

**Comment by wrabit** [comment]
@eneskaya using env outside of a config file, won't this cause issues when caching?
