### ISSUE TITLE
eb deploy

### ISSUE THREAD

**Issue by aromka** [dusterio/laravel-aws-worker#10]
Not a package issue, but just wondering how you do deployments, or if you have any tips for deployment?

Usually if you're using EB CLI, you have branch defaults in config, so doing `eb deploy` - deploys proper branch to a proper environment. Is there any way to group the environments (web + worker), so if you deploy to one - it would auto-deploy the same version to the other environment?

**Comment by EdwinDayot** [comment]
I use Buddy for this kind of stuff, but you could use Laravel Envoy for a free way of doing it (but you'll have to write code :) ).

**Comment by dusterio** [comment]
@aromka I put it all in the CI build scripts - it will choose where to deploy depending on branch. For Laravel I had to make some extra conditions in the scripts, eg. specific apps should be deployed to two destinations after every build. 

So basically just running 'eb deploy' twice, with two different destination environment names.

Couldn't find a better way with AWS...
