### ISSUE TITLE
Handle deprecated property

### ISSUE THREAD

**Issue by Sensetivity** [dusterio/laravel-aws-worker#103]
I use this package with PHP8.3 and I have next warning in my logs:

`Creation of dynamic property Dusterio\AwsWorker\Wrappers\Laravel8Worker::$cache is deprecated in /var/www/html/vendor/dusterio/laravel-aws-worker/src/Wrappers/Laravel8Worker.php`

**Comment by fylzero** [comment]
@Sensetivity thanks for letting us know and for submitting the PR!

Tagged and released - https://github.com/dusterio/laravel-aws-worker/releases/tag/v1.0.02
