### ISSUE TITLE
Messages always in Flight

### ISSUE THREAD

**Issue by andreclemente** [dusterio/laravel-aws-worker#18]
Hi, I'm using laravel 5.4 and after applying this package to my project worker, messages in my sqs stay always in flight. I've done everything that the readme file says... 

127.0.0.1 (-) - - [21/Jun/2017:01:36:59 +0000] "POST /worker/schedule HTTP/1.1" 200 92 "-" "aws-sqsd/2.3"
127.0.0.1 (-) - - [21/Jun/2017:01:37:59 +0000] "POST /worker/schedule HTTP/1.1" 200 92 "-" "aws-sqsd/2.3"
127.0.0.1 (-) - - [21/Jun/2017:01:38:59 +0000] "POST /worker/schedule HTTP/1.1" 200 92 "-" "aws-sqsd/2.3"
127.0.0.1 (-) - - [21/Jun/2017:01:39:59 +0000] "POST /worker/schedule HTTP/1.1" 200 92 "-" "aws-sqsd/2.3"
127.0.0.1 (-) - - [21/Jun/2017:01:39:54 +0000] "POST /worker/queue HTTP/1.1" 500 84128 "-" "aws-sqsd/2.3"
127.0.0.1 (-) - - [21/Jun/2017:01:40:59 +0000] "POST /worker/schedule HTTP/1.1" 200 92 "-" "aws-sqsd/2.3"
127.0.0.1 (-) - - [21/Jun/2017:01:41:13 +0000] "POST /worker/queue HTTP/1.1" 500 84128 "-" "aws-sqsd/2.3"
127.0.0.1 (-) - - [21/Jun/2017:01:41:13 +0000] "POST /worker/queue HTTP/1.1" 500 84128 "-" "aws-sqsd/2.3"
127.0.0.1 (-) - - [21/Jun/2017:01:41:13 +0000] "POST /worker/queue HTTP/1.1" 500 84128 "-" "aws-sqsd/2.3"
127.0.0.1 (-) - - [21/Jun/2017:01:41:13 +0000] "POST /worker/queue HTTP/1.1" 500 84128 "-" "aws-sqsd/2.3"
127.0.0.1 (-) - - [21/Jun/2017:01:41:13 +0000] "POST /worker/queue HTTP/1.1" 500 84128 "-" "aws-sqsd/2.3"

**Comment by ronaldwraithco** [comment]
I got the same issue. Have you figure out it yet?

**Comment by dusterio** [comment]
Do you return a HTTP status code of 200 when you process the job? AWS should delete the queue job automatically upon 200 response

**Comment by ronaldwraithco** [comment]
It only becomes 200 when I set REGISTER_WORKER_ROUTES to true.
What should I use for the queue name? The name I used in the cron.yaml or queue name in the sqs console.

**Comment by ronaldwraithco** [comment]
I figure out I don't have the permission to use the queue through the API. After I add the permission in the account, the application finally able to process the queue message.

**Comment by alwinaugustin** [comment]
I have a time-consuming process and so it is not able to return `200` before the process is completed. My process is taking around half an hour to complete and I think it will not wait for that much time to receive the response. So my messages are going to in flight mode and is triggered repeatedly in the next schedule execution.  I also try to delete the message, but it is not posting the `ReceiptHandle` back to the application and without which I can't delete the messages. Is there any workaround for this?

**Comment by gbwashleybrown** [comment]
Currently having this issue... no idea how to fix this.
