### ISSUE TITLE
Is Queue Configuration  needed for Scheduled tasks

### ISSUE THREAD

**Issue by tobsbola** [dusterio/laravel-aws-worker#19]
Hi!,

Am trying to figure out if I need to set up **Configure any queue** if all I need is just Scheduled tasks.

Thanks

**Comment by slumrig** [comment]
Its not very clear in the AWS documentation but I believe you can set up events in AWS CloudWatch that will push messages onto a queue on a schedule.

**Comment by fylzero** [comment]
Closing as stale. I do not believe a queue is explicitly required to execute scheduled tasks. This package is designed to solve for scheduling queued jobs.
