### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by ibreakshit** [dusterio/laravel-aws-worker#2]
Your documentation is unclear as to how a queue sent to SQS is processed in a Laravel/Lumen. 

First off, your `/worker/schedule` endpoint seems to be successful in firing scheduled jobs within `Console/Kernel.php` but I don't see the purpose of your code as you could just set `cron.yaml` to run whatever endpoint you want (when you want). Not to mention that your sample code `$schedule->command('inspire')` just causes more confusion. (inspire?)

I've tried sending jobs to SQS but how exactly is your code supposed to handle the jobs? Calling `/worker/schedule` does nothing unless I implement `$schedule->command('queue:work')->everyMinute();` and even if I do, I don't see what the difference is from just calling `Artisan::call('queue:work');` from any end point and have `cron.yaml` call it every minute.

**Comment by dusterio** [comment]
1) There are at least two points – first of all, you get a single point of configuration. All scheduled tasks are in PHP code, compiled using a convenient fluent API. If you use cron.yaml – you need to duplicate the same information (which tasks and when) for AWS and non-AWS environments. 

And secondly, scheduled tasks are quasi-evenly distributed among instances. AWS will fire a /worker/schedule event every minute but it will be pushed to SQS queue and processed by a _single_ EC2/EB instance. If you put it in your cron.yaml manually, either all instances will run the same task at the same time or you will have to look for a workaround/hack to make one of the instances a 'leader'. While there are solutions for this, they look way more complicated and uglier.

2) With AWS Elastic Beanstalk, every worker has a special job queue. You could just put any job directly into the queue and _one_ of the instances of your cloud will process that job. Scheduled tasks are kind of a wrapper for 'real' jobs.

3) My code doesn't handle jobs - your application should :) My package is an interface between AWS and Laravel (or Lumen) - that's it, nothing more. It will make your _standard_ scheduling and queuing tools work.

**Comment by ibreakshit** [comment]
I understand that it _might_ make sense when you're trying to implement AWS + non-AWS.

I might not be fully understanding the correct way to use your code but my goal and understanding is that multiple Laravel instances should be able to send queues via SQS to a single worker(Elastic Beanstalk Worker)for processing.

If that is the case, the single worker would need to be able to "listen" for new SQS messages, which is impossible on Elastic Beanstalk worker instances. The only option that I can think of is running `Artisan::call('queue:work');` continuously using cron.yaml. My understanding was that your code would provide an alternative way of listening to SQS messages.

**Comment by dusterio** [comment]
That is correct - my code is indeed providing an alternative way. It goes in the direction of least resistance - I'm relying upon Amazon sqsd to parse the queue and deliver the jobs. Laravel will simply receive a ready-to-deserialize payload.

It's a very important detail that using this package - you are pretty much guaranteed that each task (be it a scheduled task or a queued task) will be processed by one instance only.

If you run supervisor or regular cron inside of your worker (and some people do) - you will have to manage that manually, yourself.

If you put every scheduled task in cron.yaml - you lose a little bit of readability and opportunity to test on local machine using 'php artisan schedule:run'. This part is subjective, it's a matter of taste I suppose. I just like Laravel's scheduling API more than cron.yaml syntax so I would rather compose tasks there.

PS. It's always a hybrid AWS and non-AWS environment – I doubt there are developers who run local or development environments in Elastic Beanstalk, that would be awful :)

**Comment by ibreakshit** [comment]
Thanks so much for the explanation, it looks like I was a bit confused as to how SQS and EB Worker functioned together, everything seems to be working out as I expected!
