### ISSUE TITLE
Schedule request returns 302

### ISSUE THREAD

**Issue by ido567** [dusterio/laravel-aws-worker#20]
I've installed the package in my project, but it looks like all the requests of '/worker/schedule' returns 302 status code on EB servers.
The package works perfectly on my local machine, and I made sure that the 'REGISTER_WORKER_ROUTES' env variable is turned on.

The logs:
`/var/log/httpd/access_log:`
`127.0.0.1 (-) - - [16/Jul/2017:19:09:00 +0000] "POST /worker/schedule HTTP/1.1" 302 376 "-" "aws-sqsd/2.3"`

`/var/log/aws-sqsd/default.log:`
`2017-07-16T19:14:00Z message: sent to http://localhost:80/worker/schedule`
`2017-07-16T19:14:00Z http-err: b910dcd1-7713-429c-bfe3-2d5990e0f2fc (2) 302 - 0.037`

**Comment by bobbygrossmann** [comment]
Did you get it resolved ? Im getting same error.

**Comment by bobbygrossmann** [comment]
I hade the same issue but i figure out that App\Http\Kernal  line16 ( protected $middleware)  was holding it back, just outcomment it and my worker was fixed. However if your using same app as worker you should do a env check :)

**Comment by ido567** [comment]
My problem was that I added a package which forces all requests to be 'https' and EB requests was 'http'.
Disabling this restriction in the worker environment solved this issue.
The package uses middleware to check the protocol, so it might be your problem too.

**Comment by bobbygrossmann** [comment]
Aha yes i have same flow, will see if its that.

**Comment by edward-aslin** [comment]
This was also the problem for me. I had an Elasticbeanstalk extension file forcing HTTP redirect.

I modified this with a conditional so it didn't run on the worker, and hey presto. It works.
