### ISSUE TITLE
Does not work with Lumen 5.6

### ISSUE THREAD

**Issue by rs2801** [dusterio/laravel-aws-worker#31]
Due to how the serviceprovide has a preg match it is not passing in the correct parameter to add routes.  It should be more flexible to cater for future versions of lumen.

It should pass in app->router but is instead passing ->app only

**Comment by westonwatson** [comment]
I'm also not seeing the routes in Laravel 5.7, I'm curious as to how I can confirm this a similar issue as the above stated with Lumen 5.6...

`For now, we're manually registering these in ./routes`
