### ISSUE TITLE
I think my worker app is working fine but my main app is not creating jobs.

### ISSUE THREAD

**Issue by ronaldwraithco** [dusterio/laravel-aws-worker#37]
127.0.0.1 (-) - - [16/Mar/2018:14:19:59 +0000] "POST /worker/schedule HTTP/1.1" 200 100 "-" "aws-sqsd/2.3"

My worker post on /worker/schedule.
But my main app is not responding at all. I have set the queue driver to sqs and set the credentials. Is there anything else I have to do in the main app to create the jobs?

**Comment by zandzpider** [comment]
you can check the sqs queue in aws to see if it's delivering jobs. if it's not. then it's a laravel/config issue and not this package
