### ISSUE TITLE
Got an error after installing all the dependencies  Call to undefined method Illuminate\Foundation\Application::post()

### ISSUE THREAD

**Issue by khatri-sumankhatri** [dusterio/laravel-aws-worker#41]
Fatal error: Call to undefined method Illuminate\Foundation\Application::post() in ..local\vendor\dusterio\laravel-aws-worker\src\Integrations\LumenServiceProvider.php on line 36

**Comment by fylzero** [comment]
Marking as stale. This is likely due to a dependency conflict. If this still is presenting a problem, please open a new issue with as much detail as possible. Thanks!
