### ISSUE TITLE
Suddenly /worker/queue 404 error

### ISSUE THREAD

**Issue by basebuild** [dusterio/laravel-aws-worker#42]
Hi, I've been using this in my project. Everything was working fine and then suddenly I get a 404 error. http://prntscr.com/km7t9q

This has happened to me before, re-creating the worker worked but I did that twice already and same problem happens again. I do not want to re-create the server again.

Please help me ASAP.

**Comment by basebuild** [comment]
I came back to let you know that this is more like a server issue.

**Comment by robincsamuel** [comment]
@basebuild Facing the same. It'd be great if you can share what exactly was the issue. :) 
Thanks!

**Comment by robincsamuel** [comment]
It worked after a restart for me, not sure about the root cause.
