### ISSUE TITLE
Messages Remain In Flight

### ISSUE THREAD

**Issue by hzburki** [dusterio/laravel-aws-worker#47]
I have set up both my Web Tier as well as my Worker Tier with the same App. The web tier has 
`REGISTER_WORKER_ROUTES=false` whereas the worker tier has `REGISTER_WORKER_ROUTES=true`.

I am pushing a job to SQS which simply edits an attribute in the database. But every time I push a new job it increments the counter **Messages In Flight** and nothing else happens.

**Comment by Juhlinus** [comment]
I'm having this issue as well.

@hzburki did you manage to solve this?

**Comment by hzburki** [comment]
@Juhlinus I can't help you ... I had to start the process from the beginning. And everything fell into place. I wasn't able to pin point what I was doing wrong. Sorry

**Comment by Juhlinus** [comment]
I actually had the exact same experience! Thanks anyway!
