### ISSUE TITLE
Issue with WithoutOverLapping and Max tries 

### ISSUE THREAD

**Issue by vijaykumar1** [dusterio/laravel-aws-worker#52]
I have two issues with my worker. How can I solve these two issues?

**1.  WithoutOverLapping:**
Ex: I have One job which runs every 5 mins. But sometimes the job might take more than 5 mins. In order to avoid multiple overlapping jobs, Laravel has a WithoutOverLapping concept. It is not working ( not even triggering the job) with the package. Is there any workaround? Or any plans to add support?
```
$schedule
            ->command('test:command')
            ->everyFiveMinutes()
            ->withoutOverlapping();
```

**2. MaxTries:** It seems that there is an existing issue. I saw a PR which is not released yet. Any plan to add this support?

**Comment by tibinvpaul** [comment]
Hello @dusterio - is there anything to do with the package for `WithoutOverLapping not working` issue? Thanks in advance.

**Comment by ShabihZaidi** [comment]
Hey @dusterio, Is there any workaround for jobs not getting triggered when `withoutOverlapping` is specified?

**Comment by fylzero** [comment]
@ShabihZaidi and @vijaykumar1 Currently this is not supported but if a PR is submitted and documented to where it can be easily tested and does not include breaking changes, we will gladly pull it in.
