### ISSUE TITLE
Please allow Laravel v6 in your composer file.

### ISSUE THREAD

**Issue by fylzero** [dusterio/laravel-aws-worker#54]
Laravel 6 was officially released today.  They are simply moving to SemVer and should not be considered a major breaking change update.  Please allow your package to include illuminate/support ^6.0

**Comment by fylzero** [comment]
I created a PR for this.

**Comment by d3radicated** [comment]
Just commenting here that Laravel 6 support has been released.

**Comment by fylzero** [comment]
Thank you!
