### ISSUE TITLE
Throwing Exception

### ISSUE THREAD

**Issue by rgundapu** [dusterio/laravel-aws-worker#56]
Error : exception 'Dusterio\AwsWorker\Exceptions\MalformedRequestException' with message 'Unable to decode request JSON'

**Comment by tvillafane** [comment]
You might need to base64 encode your job parameters when you instantiate your job and decode on handle.  I had this issue with emails and I ended up having to encode the body when I passed it to the job.

**Comment by fylzero** [comment]
Closing as stale. Please open a new issue if this is still presenting a problem. Thanks!
