### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by aaronflorey** [dusterio/laravel-aws-worker#6]
Hello,

How do i set up the queue with this? I don't see any explanation on how the queue works. How does AWS know to push it to that specific route?

I'm a bit confused.

**Comment by dusterio** [comment]
@Mochaka when you create a worker environment in AWS, it forces you either to create a new SQS queue or choose an existing one. So there is always a queue associated with a worker.

Then, you just set environment variables to tell Laravel about that queue - QUEUE_DRIVER, S3_KEY, S3_SECRET and so on (see config/queue.php). 

I guess I should improve the README :)

**Comment by aaronflorey** [comment]
Ohhh, forgot totally about the worker tier and didn't know it subscribed to SQS. Thanks for that, might want to add that to the README so nubs can understand 🤓
