### ISSUE TITLE
Please support minor versions of Laravel 6.x

### ISSUE THREAD

**Issue by colinpizarek** [dusterio/laravel-aws-worker#61]
Running Laravel 6.2, receiving this error:

> ERROR: Argument 3 passed to Illuminate\Queue\Worker::process() must be an instance of Illuminate\Queue\WorkerOptions, integer given, called in /var/app/current/vendor/dusterio/laravel-aws-worker/src/Wrappers/DefaultWorker.php on line 31

I can see the error is in  `\Integrations\BindsWorker`. All supported minor versions are hardcoded here:

```
   /**
     * @var array
     */
    protected $workerImplementations = [
        '5\.[345678]\.\d+' => Laravel53Worker::class,
        '6\.[01]\.\d+' => Laravel6Worker::class
    ];
```

Minor versions are going to be coming faster than before, so I suspect this approach is not sustainable.

**Comment by dusterio** [comment]
@colinpizarek sure, I've just changed it to a more generic expression! thanks for noticing and reporting this

**Comment by colinpizarek** [comment]
Much appreciated, thank you.
