### ISSUE TITLE
The command "schedule" does not exist. v0.1.21

### ISSUE THREAD

**Issue by alietors** [dusterio/laravel-aws-worker#62]
We just updated to the new version and we receive the following error
```The command "schedule" does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): The command \"schedule\" does not exist. at /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Application.php:178)```

Can it be related with the new cron option functionality? We are not using such functionality we are sticking with the classic schedule.

**Comment by dusterio** [comment]
@alietors oops you are right, I made a typo in the constant. I've just pushed and tagged a fix! sorry for this

**Comment by ruizr-ignacio** [comment]
I have this error v0.1.22 => 

`The command "laravel task" does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): The command \"laravel task\" does not exist. at /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Application.php:179)`
