### ISSUE TITLE
When queued mail includes routes(), It generate http://localhost 

### ISSUE THREAD

**Issue by yamotuki** [dusterio/laravel-aws-worker#64]
SQS daemon request to `localhost` in ElasticBeanstalk worker environment.
When the queued mail processed by worker and its mail include `routes()` laravel helper function, It doesn't work as I expected. 

For example, 

- In the site of `https://example.com`, user requests and then the mail does not accumulate in queue is processed.  `route('dummy')` generate `https://example.com/dummy`.
- On the other hand, when the mail queued, the `routes()` helper function generate `https://localhost/dummy`

The reason is that `routes()' depends on `$request->root()`. 

To Prevent this problem, there are some solutions.

OUT of this library, I set `APP_ENV='https://example.com'` and then the program register to AppServiceProvider.
```
if (env('REGISTER_WORKER_ROUTES', true)) {
    URL::forceRootUrl(config('app.url'));
}
```

If I fix IN this library, I may add program bellow and write note to readme.
```laravel-aws-worker/src/Integrations/LaravelServiceProvider.php
    public function register()
    {
        if (function_exists('env') && ! env('REGISTER_WORKER_ROUTES', true)) return;
        
        URL::forceRootUrl(config('app.url'));
        ...
    }
```

 I'd really appreciate it if you could give me your opinion.

**Comment by dusterio** [comment]
@yamotuki its a known problem - Laravel behind CDN/load-balancers breaks the URLs. Our solution is the same as yours -  url->forceRootUrl(config('app.url')), looks redundant but it helps ;)
