### ISSUE TITLE
Delayed Dispatching Issue with Auto-Scale or Server Failure

### ISSUE THREAD

**Issue by TheTiki** [dusterio/laravel-aws-worker#68]
I noticed that the delayed job dispatch will hold the job on the server until the delay time is met, and then send it to SQS. This means that if a server goes down before the job is triggered and sent to SQS, it will not be sent at all and thus never run. Is there a way to circumvent this or incorporate better support for laravel job dispatching delays?

**Comment by dusterio** [comment]
@TheTiki no, this shouldn't be the case - SQS delay is handled by Amazon, so your app sends the message right away. The maximum delay is 15 minutes though. See more https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-delay-queues.html
