### ISSUE TITLE
AWS worker returns error 500. Message always in flight

### ISSUE THREAD

**Issue by adityar15** [dusterio/laravel-aws-worker#71]
I am using Laravel 7.0 and dusterio laravel-aws-worker package for processing SQS jobs. Things work well on php artisan queue:work.

However, when I deploy the application with REGISTER_WORKER_ROUTES=true in .env file, it fails to process the job. The message always go in flight.

`
127.0.0.1 (-) - - [07/Mar/2020:10:12:08 +0000] "POST /worker/queue HTTP/1.1" 500 1558 "-" "aws-sqsd/2.4"
127.0.0.1 (-) - - [07/Mar/2020:10:13:15 +0000] "POST /worker/queue HTTP/1.1" 500 1558 "-" "aws-sqsd/2.4"
127.0.0.1 (-) - - [07/Mar/2020:10:15:27 +0000] "POST /worker/queue HTTP/1.1" 500 1558 "-" "aws-sqsd/2.4"
`

It gives the errors above in the log file. The worker can poll the message but fails after that with 500 error

`
2020-03-07T10:12:08Z message: sent to http://localhost:80/worker/queue
2020-03-07T10:12:08Z http-err: 9e3c4a8c-967d-4e5f-9ce5-e974af2a4394 (8) 500 - 0.016
2020-03-07T10:13:15Z message: sent to http://localhost:80/worker/queue
2020-03-07T10:13:15Z http-err: 2387ed18-3b2a-4b17-ae5f-9cc6e94f92db (3) 500 - 0.020
2020-03-07T10:15:27Z message: sent to http://localhost:80/worker/queue
2020-03-07T10:15:27Z http-err: 07d12647-1e34-4a7c-9dc3-e9637e3a6793 (1) 500 - 0.015
`

I have followed the tutorial on Github to cofigure the AWS worker env. It was working fine but now its throwing error.

Can anyone please help me through this? Thanks :)

**Comment by dusterio** [comment]
@adityar15 I'm going to take a look at this shortly!

**Comment by adityar15** [comment]
That would really be appreciated. Thanks @dusterio

**Comment by dusterio** [comment]
@adityar15 since its a 500 error, there must be a proper exception in the laravel.log file?

**Comment by adityar15** [comment]
@dusterio thanks for the reply. I tried to check the log file and was not able to do it. So I sorted the issue by installing the supervisor and making it poll the messages. It worked perfectly.

**Comment by dusterio** [comment]
@adityar15 the problem with this approach (supervisor) is that you will be polling even when the queue is empty. with AWS workers, you can rely on AWS to only send you a POST request when there is an actual job in the queue, it's already implemented by AWS
