### ISSUE TITLE
Laravel 7 no support in BindsWorker

### ISSUE THREAD

**Issue by Nilanth** [dusterio/laravel-aws-worker#72]
Getting this issue after updating laravel to 7.

Argument 3 passed to Illuminate\Queue\Worker::process() must be an instance of Illuminate\Queue\WorkerOptions, int given, called in /var/app/current/vendor/dusterio/laravel-aws-worker/src/Wrappers/DefaultWorker.php on line 31

In \Integrations\BindsWorker. : no support for laravel 7

   ```
/**
     * @var array
     */
    protected $workerImplementations = [
        '5\.[345678]\.\d+' => Laravel53Worker::class,
        '6\.[01]\.\d+' => Laravel6Worker::class
    ];
```
Could you please add support fot laravel 7?

**Comment by dusterio** [comment]
@Nilanth I'll take a look at this shortly - tomorrow or the day after! thanks for reporting

**Comment by Nilanth** [comment]
> @Nilanth I'll take a look at this shortly - tomorrow or the day after! thanks for reporting

@dusterio is there any update on this?

**Comment by dusterio** [comment]
@Nilanth can you try again please? It should be ok now, works for me

**Comment by Nilanth** [comment]
> @Nilanth can you try again please? It should be ok now, works for me

@dusterio Thanks it's working now.
