### ISSUE TITLE
SECURITY: Set default of REGISTER_WORKER_ROUTES  to false

### ISSUE THREAD

**Issue by fschirinzi** [dusterio/laravel-aws-worker#75]
Hi Denis!

Thank you for this package, it's really helpful.

I have concerns about the security of this package.
Wouldn't it be better to set the default of the `REGISTER_WORKER_ROUTES`to  `false`, here my points:

If one forgets to set it to true,
- one will notice it pretty soon. (No emails are sent, no jobs are run)
- nothing bad happens, since the endpoints are closed

I could just fork the package and fix it for me, but I think it would be better for every user (especially the beginners) to fix this in the main package and make the internet a little saver. 

What do you think about it?
Is there a reason to set the default to `false` that I don't see?

**Comment by dusterio** [comment]
@fschirinzi I agree with you, and I can't remember why I chose to do it this way, there must have been a reason :) please give me a day to try to remember what it was

**Comment by fschirinzi** [comment]
Any updates here? :)
Should I do a Pull-request?

**Comment by Uplink03** [comment]
This is an awesome way to run _any_ `artisan` command from the Internet on random websites that deploy this package 🥇  `down`, for example, is a good start.

**Comment by dusterio** [comment]
@fschirinzi yes a PR please :)

**Comment by fschirinzi** [comment]
Hi @dusterio, this issue is already 2 years old, and I'm not using this package any more since a long time now.
I will not be able to do a PR, sorry. You can close this issue if you like.
