### ISSUE TITLE
Scheduler seems to execute tasks as root user

### ISSUE THREAD

**Issue by flefloch-payps** [dusterio/laravel-aws-worker#76]
Hello,

first of all thanks for this package.
I'm not sure this issue is related to the package or to an error in EB configuration, but it seems that the tasks are run by a root user and not webapp user. 
I have a task run each day at midnight and among others it's creating the new daily log file and a tmp file, and both seems to be created with limited root access. So classic webapp user which runs the app can't access these files.
Anyone has ever met this issue?
Do I need to configure the user somewhere?

Thank you.

**Comment by fylzero** [comment]
Marking this as stale. This is likely a non-package-related config issue.
