### ISSUE TITLE
Can't access variables off job class

### ISSUE THREAD

**Issue by mrozbarry** [dusterio/laravel-aws-worker#77]
On a project, we have a parent abstract class:

```
abstract class TransactionJob implements ShouldQueue
{
  use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

  public $jobId;

  public function __construct($jobPrefix = 'job') {
    $this->jobId = sprintf('%s_%s', $jobPrefix, bin2hex(random_bytes(6)));
  }

  public function handle() {
    // ...
    $this->transactionHandle();
    // ...
  }

  public function log($format, ...$args) {
    Log::info(sprintf('Job[%s]: %s', $this->jobId, sprintf($format, ...$args));
  }

  abstract public function transactionHandle();
}

// ...

class SomeJob extends TransactionJob
{
  public __construct() {
    parent::__construct('SomeJob');
  }

  public function transactionHandle() {
    $this->log('I cant read the job id, this makes me %s', 'sad'); // Logs "Job[]: I cant rea..." but should be "Job[SomeJob_<random>]: I cant rea...."
    dd($this->jobId); // Prints nothing
  }
}
```

All of our classes that extend TransactionJob, but when we use `$this->log('stuff')`, it never seems to be able to read `$this->jobId`, and in fact, I don't seem to get anything from `$this->`, whether it's public/protected/private.

I'm not a Laravel expert, but the docs for Laravel 6.x seem to indicate this is mostly correct. Your docs mention something about a json `{ job, data }` format is required, but it's not clear to me if that's what I'm using or not.

**Comment by fylzero** [comment]
Marking as stale. Inside a job to do this I believe you would use getJobId [https://laravel.com/api/10.x/Illuminate/Contracts/Queue/Job.html#method_getJobId]()
