### ISSUE TITLE
Schedule not working - HTTP 301 

### ISSUE THREAD

**Issue by enkay** [dusterio/laravel-aws-worker#8]
I've installed the package and set up a worker environment with the cron.yaml file, however it doesn't seem like the schedule method is being run.

From the worker's access log:

`127.0.0.1 (-) - - [26/Oct/2016:21:16:59 +0000] "POST /worker/schedule HTTP/1.1" 301 225 "-" "aws-sqsd/2.3"`

Do you have any idea what could be the issue here?

**Comment by dusterio** [comment]
Hmm, 301 is a permanent redirect - and it's not used anywhere in the package or controller

Do you have redirects anywhere in your application, in other routes?

**Comment by enkay** [comment]
If I set the REGISTER_WORKER_ROUTES variable to true on the production environment, and I send a post request to /worker/schedule on the website it works.

It's just in the worker environment that it doesn't work, it sends a message to http://localhost:80/worker/schedule and it gives an http-err.

I do have redirects on other routes, but I don't know why it would be hitting those on the worker and not in production. I also have redirects in my htaccess, but even removing them I always get the same 301 redirect response from the worker environment in the access log.

Edit: Could it have to do with the worker environment being in a VPC? But then so is the production environment.

**Comment by enkay** [comment]
Could it have to do with the worker environment being in a VPC? But then so is the production environment.

**Comment by dusterio** [comment]
Do you have your web application running in worker environment? VPC shouldn't be an issue - Amazon makes those calls from inside, also you wouldn't see anything in the log if AWS couldn't reach you

**Comment by enkay** [comment]
The problem was with a .ebextensions file that was setting a redirect. Thanks for your help.
