### ISSUE TITLE
Broken Laravel 7 worker support

### ISSUE THREAD

**Issue by mfurgal** [dusterio/laravel-aws-worker#80]
Hello, 

In Laravel7Worker.php:34 WorkerOptions object is created as if it was Laravel 8 (passing value for $name) causing unexpected behaviour.

We have:
```
        $workerOptions = new WorkerOptions('default', $options['delay'], 128, $options['timeout'], 3, $options['maxTries']);
```
We should have: 
```
        $workerOptions = new WorkerOptions($options['delay'], 128, $options['timeout'], 3, $options['maxTries']);
```

Additionally in WorkerController.php:150 we now have default value for maxTries set to 1 but it was 0 before and it also changes how app interacts with queue.

**Comment by dusterio** [comment]
@mfurgal thanks for reporting this quickly, I've just restored the old format for Laravel 7, as well as the default value of maxTries

**Comment by mfurgal** [comment]
@dusterio Thank you!
