### ISSUE TITLE
No routes in routes list - laravel 8

### ISSUE THREAD

**Issue by Gatts011** [dusterio/laravel-aws-worker#85]
@dusterio can you confirm this is working in laravel 8? Not seeing routed in route:list

**Comment by dusterio** [comment]
@Gatts011 yep it does, we use it heavily in our setup

**Comment by Gatts011** [comment]
Thanks, just tried uploading and works well, even with fifo! routes
didnt show on list command locally but who cares!
thanks a ton, saved a life today!

**Comment by Gatts011** [comment]
Sorry to bug you again,

Im using

RemoveLTDReservation::dispatch($sessionId, $cartKey, $uniqueId)
        ->delay(now()->addMinutes(1));

for delay on message, but delay is never triggered, always instantly
consumed.
I have set delay in SQS Queue, also no effect,
tried setting delay in controller, same thing.
Im using a standard SQS queue(not fifo).

Im sure the error is my side, just want to know how you would normally set
a delay?

Also I wasn't using fifo before in worker app, to correct myself, not sure
it it works.

Thanks again

Toby French
