### ISSUE TITLE
How to define max "workers" (max simultaneous task per worker server)

### ISSUE THREAD

**Issue by mtx-z** [dusterio/laravel-aws-worker#89]
Hello,

I'm using this package to handle the queue system between 2 Beanstalk instantiated EC2. One dispatching task, the other listening and executing queued messages. This works great. 

But, when dispatching many tasks, my "task" server is going crazy as executing many tasks in parallel. The "queue" lost its interest in this case. 

I tried to reduce the number of "HTTP connections", but I still see many HTTPD process high CPU on the server, and on SQS I see many "in progress" messages. 

How can I control the number of the parallel tasks my worker can handle? Leaving the rest in the queue to be processed after? 

Thanks

**Comment by mtx-z** [comment]
UPDATE:

The max HTTP connections seem to be the way to define "max workers" and so parallel tasks. 
I set max HTTP connections, and I can see max 5 HTTPD process consuming when checking on SSH with HTOP.

But:

- In AWS SQS interface, I still see 20 to 60 "in flight" messages. Why? It should be 5 max.
- some HTTPD process are kept running, consuming memory, and keeping X of my 5 connection active. And so the queue doesn't start more task. Those HTTPD process don't take CPU, but still keep 20% of my RAM each, and so my task server will start to throw out of memory errors... 
- I double-checked that all my queued job and listeners are returning a value, to respond HTTP 200 to SQS

Any idea? ty

**Comment by dusterio** [comment]
@mtx-z you can configure this in AWS EB settings? It's not a part of the package, the package itself cannot regulate how many tasks is it going to process in parallel. your worker environment in AWS will have settings such as task time out, maximum number of parallel tasks, etc
