### ISSUE TITLE
Error token mismatch

### ISSUE THREAD

**Issue by graphem** [dusterio/laravel-aws-worker#9]
Not sure exactly what I am doing wrong but seems I am getting this on the worker schedule on AWS EB worker instance:

worker.ERROR: Illuminate\Session\TokenMismatchException in /var/app/current/bootstrap/cache/compiled.php:3227

So seems like the route is looking for Csrf token.

Do I simply need to exlude the route from the token verification?

**Comment by dusterio** [comment]
Yep, absolutely right - just remove CSRF middleware from these routes!

**Comment by graphem** [comment]
Yes it works, thanks! Might be an idea to add to the doc. Great package by the way, love it.
