### ISSUE TITLE
Question: is there support for the backoff option on job retries?

### ISSUE THREAD

**Issue by gregory-claeyssens** [dusterio/laravel-aws-worker#94]
Hey, 

I posted [this question on SO](https://stackoverflow.com/questions/75898283/laravel-queued-job-with-a-backoff-not-working-on-sqs).
I realized afterwards that it might be something that isn't supported by this package though. Hence my 'repost' here.
Any information would be truely appreciated.

**Comment by fylzero** [comment]
@gregory-claeyssens The backoff option is available with queue:work but I don't believe this is possible when deployed to EB. We don't have code passing this option anywhere, I'm not exactly sure how that could work. Apologies for the delayed response!

**Comment by gregory-claeyssens** [comment]
No problem @fylzero in the meantime life went on without this feature as well :)
I do think it should technically be possible, since [AWS SQS allows delays up to 15min](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-delay-queues.html) and workers are simply simply environments waiting for jobs from SQS. Laravel also supports delayed dispatching (see [docs](https://laravel.com/docs/11.x/queues#delayed-dispatching), and it also notes that SQS is limited to 15min max)

**Comment by fylzero** [comment]
@gregory-claeyssens You are welcome to submit a PR if you'd like. We just decided to drop Lumen support which will make our review and testing process a bit easier now.
