### ISSUE TITLE
Laravel aws worker clobbers horizon/redis queue configuration

### ISSUE THREAD

**Issue by mrozbarry** [dusterio/laravel-aws-worker#96]
See https://github.com/laravel/horizon/issues/282

The queue connections gets cleared when the service provider from this package creates a new queue manager.

We did some experiments on my team and where able to process queued jobs using laravel's SyncJob class after consuming the data from sqsd. Not sure if that limits which laravel versions are compatible, but we didn't need to create a QueueManager singleton in our experiment (on an empty laravel 10 project).

We'd be willing to do a PR, but we're not certain if that would affect lumen, or break laravel 6 support.

**Comment by fylzero** [comment]
@mrozbarry We've recently chosen to drop Lumen support for future versions. If this makes submitting a PR useful or possible now you are welcome to do so.
