### ISSUE TITLE
Unresolvable dependency resolving [Parameter #3

### ISSUE THREAD

**Issue by rizwansaleem786** [dusterio/laravel-aws-worker#97]
I have integrated the following package with my lumen microservice to listen jobs on aws worker. But when I receive the job on aws worker it get crashed with following error
`[2023-07-26 13:41:22] staging.ERROR: Unresolvable dependency resolving [Parameter #3 [ <required> callable $isDownForMaintenance ]] in class Illuminate\Queue\Worker {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Unresolvable dependency resolving [Parameter #3 [ <required> callable $isDownForMaintenance ]] in class Illuminate\\Queue\\Worker at /var/app/current/vendor/illuminate/container/Container.php:1104)`

Composer.json
"require": {
        "php": "^8.0",
        "aws/aws-sdk-php-laravel": "^3.6",
        "doctrine/dbal": "^3.6",
        "dusterio/laravel-aws-worker": "^0.1.38",
        "dusterio/lumen-passport": "^0.3.4",
        "fruitcake/laravel-cors": "^2.0",
        "laravel/lumen-framework": "^8.3.1",
        "laravel/passport": "^10.2",
        "league/flysystem-aws-s3-v3": "^3.15",
        "niellles/lumen-commands": "^1.0",
        "pearl/lumen-request-validate": "^1.6",
        "php-amqplib/php-amqplib": "^3.5",
        "ramsey/uuid": "^4.2",
        "tzsk/collage": "^6.0",
        "vlucas/phpdotenv": "^5.5"
    },

I am facing same error on every lumen base worker.
How I can fix this issue

**Comment by fylzero** [comment]
@rizwansaleem786 From what I can tell this issue comes up during upgrade paths in Laravel and Lumen. See if the below articles help guide a solution. Unfortunately I don't have much other information on this.

https://laracasts.com/discuss/channels/laravel/unresolvable-dependency-isdownformaintenance
https://github.com/laravel/framework/issues/29724#issuecomment-551087331
