### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by timmylindh** [dusterio/laravel-aws-worker#99]
Hi,

Are you planning to support Laravel 11?

**Comment by fylzero** [comment]
@timmylindh We've already bumped dependencies up to v11. Let us know if you run into any issues.

**Comment by timmylindh** [comment]
> @timmylindh We've already bumped dependencies up to v11. Let us know if you run into any issues.

Not in the latest version I think? Do I have to run the master branch?

**Comment by fylzero** [comment]
@timmylindh Just went ahead and tagged the [release v0.1.39](https://github.com/dusterio/laravel-aws-worker/releases/tag/v0.1.39)

**Comment by timmylindh** [comment]
Thanks alot!

**Comment by fylzero** [comment]
@timmylindh You too, thanks!
